In [1]:
import pandas as pd
import numpy as np

In [ ]:


#Create a public URL
#https://docs.google.com/spreadsheets/d/1S9kV13rNGrMQAKpOhRJW9tI0LimT6Jw6T2HPdIz00W0/edit?gid=0#gid=0 construction
#https://docs.google.com/spreadsheets/d/1S9kV13rNGrMQAKpOhRJW9tI0LimT6Jw6T2HPdIz00W0/edit?gid=1413065181#gid=1413065181 developer

#get spreadsheets key from url
gsheetke_construction = "1S9kV13rNGrMQAKpOhRJW9tI0LimT6Jw6T2HPdIz00W0"

#sheet name
sheet_name = 'construction'

url=f'https://docs.google.com/spreadsheet/ccc?key={gsheetkey}&output=xlsx'
df = pd.read_excel(url,sheet_name='1',index_col=0)

In [21]:
sheet_name = 's_construction' # replace with your own sheet name
sheet_id = '1S9kV13rNGrMQAKpOhRJW9tI0LimT6Jw6T2HPdIz00W0' # replace with your sheet's ID

In [22]:
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

In [23]:
df = pd.read_csv(url)

In [24]:
df

,Регион,Строящихся домов ед.,%,"Жилых единиц ед.( квартиры, аппартаменты)",%.1,Совокупная S жилых единиц S м2,%.2
0,Москва,748.0,"6,30%",378 635,"15,40%",19 853 154,"16,50%"
1,Московская область,715.0,"6,10%",205 834,"8,40%",9 368 045,"7,80%"
2,Краснодарский край,853.0,"7,20%",203 138,"8,30%",9 282 715,"7,70%"
3,Санкт-Петербург,449.0,"3,80%",168 300,"6,80%",7 081 476,"5,90%"
4,Свердловская область,403.0,"3,40%",105 516,"4,30%",5 009 636,"4,20%"
...,...,...,...,...,...,...,...
80,Республика Алтай,11.0,"0,10%",1 013,"0,00%",46 248,"0,00%"
81,Республика Ингушетия,3.0,"0,00%",344,"0,00%",28 680,"0,00%"
82,Луганская Народная Республика,3.0,"0,00%",421,"0,00%",24 752,"0,00%"
83,Мурманская область,1.0,"0,00%",100,"0,00%",5 271,"0,00%"
84,Общий итог,NaN,100%,"2 459 820,0",100%,120 677 244,100%